export const PICKER_CONTENT_CLASS = 'flex flex-col gap-12 relative w-full px-5 pb-[max(1.5rem,env(safe-area-inset-bottom))] pt-7 tablet:px-7 tablet:pt-9';
export const PICKER_CLOSE_BUTTON_CLASS = 'absolute right-3 -top-3 flex h-9 w-9 items-center justify-center rounded-full text-theme-text-secondary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-theme-accent';
export const PICKER_TITLE_CLASS = 'text-center  text-xl font-semibold tracking-tight text-theme-text-primary';
export const PICKER_DESCRIPTION_CLASS = 'min-h-6 flex justify-center items-center text-base text-theme-text-secondary';
export const PICKER_BODY_CLASS = 'py-3 w-full min-w-0';
export const PICKER_ACTIONS_CLASS = 'w-full';
const PICKER_BUTTON_BASE_CLASS = 'flex min-h-12 w-full items-center justify-center rounded-full px-5  text-base text-theme-text-on-accent transition-opacity focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:cursor-not-allowed disabled:opacity-40';
export const PICKER_CONFIRM_BUTTON_CLASS = `${PICKER_BUTTON_BASE_CLASS} bg-theme-accent focus-visible:outline-theme-accent`;
export const PICKER_DANGER_BUTTON_CLASS = `${PICKER_BUTTON_BASE_CLASS} bg-theme-danger focus-visible:outline-theme-danger`;
